<?php

declare(strict_types=1);

namespace Manifesto\Services;

use Manifesto\Repositories\ProjectRepository;
use Manifesto\Repositories\ServiceRepository;

/**
 * Generates Dockerfile content for services that declare a build_context.
 * Stateless — every call is self-contained; no I/O is performed inside.
 */
final class DockerfileGenerator
{
    public function __construct(
        private ProjectRepository $projects,
        private ServiceRepository $services,
    ) {
    }

    /**
     * Returns the Dockerfile content for a single service, or null when the
     * service does not have a build_context.
     *
     * If build_context is set but dockerfile_content is empty/null, a minimal
     * default Dockerfile is generated from the service image: `FROM <image>`.
     */
    public function generateForService(int $serviceId): ?string
    {
        $service = $this->services->find($serviceId);
        if ($service === null) {
            return null;
        }

        $buildContext = $service->buildContext ?? null;
        if (empty($buildContext)) {
            return null;
        }

        $content = $service->dockerfileContent ?? '';
        if (trim((string) $content) === '') {
            $content  = "# Auto-generated Dockerfile (no inline content provided)\n";
            $content .= 'FROM ' . $service->image . "\n";
        }

        $header  = '# Generated by Manifesto · service: ' . $service->name . ' · ' . date('c') . "\n";
        $header .= '# build_context: ' . $buildContext . "\n\n";

        return $header . $content;
    }

    /**
     * Generates Dockerfiles for all services in a project that have a build_context.
     *
     * @return array<string,string> Map of service name => Dockerfile content.
     */
    public function generateForProject(int $projectId): array
    {
        $serviceRows = $this->projects->servicesOf($projectId);
        $result      = [];

        foreach ($serviceRows as $row) {
            $content = $this->generateForService((int) $row['id']);
            if ($content !== null) {
                $result[(string) $row['name']] = $content;
            }
        }

        return $result;
    }
}
