<?php

declare(strict_types=1);

namespace Manifesto\Services;

use Manifesto\Models\EnvVar;
use Manifesto\Models\PortMapping;
use Manifesto\Models\Volume;
use Manifesto\Repositories\ProjectRepository;
use Manifesto\Repositories\ServiceChildrenRepository;
use Manifesto\Repositories\ServiceRepository;

/**
 * Generates a Docker Compose v3.8 YAML string from the project hierarchy stored in
 * the database. Stateless: every call to generate() is self-contained.
 *
 * Output format:
 *   version: "3.8"
 *   services:
 *     <name>:
 *       image: <image>  (or build: when build_context is set)
 *       restart: <policy>
 *       command: <cmd>  (omitted when null)
 *       working_dir: <dir>  (omitted when null)
 *       network_mode: <mode>  (omitted when null)
 *       depends_on:  (omitted when null)
 *       ports:   (omitted when empty)
 *       environment:  (omitted when empty)
 *       volumes:  (omitted when empty)
 *       healthcheck:  (omitted when null)
 *
 * String values that contain ':', '#', single-quote, or leading/trailing
 * whitespace are double-quoted. Null env-var values are emitted as bare keys.
 * Secret values are included — they are part of the service contract.
 */
final class DockerComposeGenerator
{
    public function __construct(
        private ProjectRepository $projects,
        private ServiceChildrenRepository $children,
        private ServiceRepository $services,
    ) {
    }

    /** @throws \RuntimeException when the project does not exist or a service name is invalid */
    public function generate(int $projectId): string
    {
        $project = $this->projects->find($projectId);
        if ($project === null) {
            throw new \RuntimeException("Project #{$projectId} not found.");
        }

        $serviceRows = $this->projects->servicesOf($projectId);

        $lines = [];
        $lines[] = '# Generated by Manifesto · ' . $project->name . ' · ' . date('c');
        $lines[] = 'version: "3.8"';
        $lines[] = '';
        $lines[] = 'services:';

        foreach ($serviceRows as $row) {
            $serviceId     = (int) $row['id'];
            $serviceName   = (string) $row['name'];
            $image         = (string) $row['image'];
            $restartPolicy = (string) $row['restart_policy'];

            // Fetch full service model for extended fields (Group 1 adds these columns).
            $service = $this->services->find($serviceId);

            $buildContext       = $service !== null ? ($service->buildContext ?? null) : null;
            $command            = $service !== null ? ($service->command ?? null) : null;
            $workingDir         = $service !== null ? ($service->workingDir ?? null) : null;
            $dependsOn          = $service !== null ? ($service->dependsOn ?? null) : null;
            $healthcheckCmd     = $service !== null ? ($service->healthcheckCmd ?? null) : null;
            $healthcheckInterval = $service !== null ? ($service->healthcheckInterval ?? null) : null;
            $networkMode        = $service !== null ? ($service->networkMode ?? null) : null;

            $this->assertValidServiceName($serviceName);

            $ports   = $this->children->portsOf($serviceId);
            $envVars = $this->children->envsOf($serviceId);
            $volumes = $this->children->volumesOf($serviceId);

            $lines[] = '  ' . $serviceName . ':';

            // 1. image / build
            if (!empty($buildContext)) {
                $lines[] = '    build:';
                $lines[] = '      context: ' . $this->yamlScalar($buildContext);
                $lines[] = '      dockerfile: Dockerfile';
                // Also emit image for `docker compose build` tagging.
                $lines[] = '    image: ' . $this->yamlScalar($image);
            } else {
                $lines[] = '    image: ' . $this->yamlScalar($image);
            }

            // 2. restart
            $lines[] = '    restart: ' . $this->yamlScalar($restartPolicy);

            // 3. command
            if (!empty($command)) {
                $lines[] = '    command: ' . $this->yamlScalar((string) $command);
            }

            // 4. working_dir
            if (!empty($workingDir)) {
                $lines[] = '    working_dir: ' . $this->yamlScalar((string) $workingDir);
            }

            // 5. network_mode
            if (!empty($networkMode)) {
                $lines[] = '    network_mode: ' . $this->yamlScalar((string) $networkMode);
            }

            // 6. depends_on (comma-separated string → YAML list)
            if (!empty($dependsOn)) {
                $lines[] = '    depends_on:';
                foreach (array_filter(array_map('trim', explode(',', (string) $dependsOn))) as $dep) {
                    $lines[] = '      - ' . $this->yamlScalar($dep);
                }
            }

            // 7. ports
            if ($ports !== []) {
                $lines[] = '    ports:';
                foreach ($ports as $port) {
                    $lines[] = '      - ' . $this->yamlScalar($this->formatPort($port));
                }
            }

            // 8. environment
            if ($envVars !== []) {
                $lines[] = '    environment:';
                foreach ($envVars as $env) {
                    $lines[] = '      ' . $this->formatEnvLine($env);
                }
            }

            // 9. volumes
            if ($volumes !== []) {
                $lines[] = '    volumes:';
                foreach ($volumes as $volume) {
                    $lines[] = '      - ' . $this->yamlScalar($this->formatVolume($volume));
                }
            }

            // 10. healthcheck
            if (!empty($healthcheckCmd)) {
                $interval = (!empty($healthcheckInterval)) ? (string) $healthcheckInterval : '30s';
                $lines[] = '    healthcheck:';
                $lines[] = '      test: ["CMD-SHELL", ' . $this->yamlScalar((string) $healthcheckCmd) . ']';
                $lines[] = '      interval: ' . $interval;
                $lines[] = '      timeout: 5s';
                $lines[] = '      retries: 3';
            }
        }

        return implode("\n", $lines) . "\n";
    }

    // -------------------------------------------------------------------------
    // Private helpers
    // -------------------------------------------------------------------------

    /**
     * Validates that a service name is a safe YAML key:
     * only alphanumerics, hyphens, and underscores.
     *
     * @throws \RuntimeException
     */
    private function assertValidServiceName(string $name): void
    {
        if (!preg_match('/^[a-zA-Z0-9_-]+$/', $name)) {
            throw new \RuntimeException(
                "Service name \"{$name}\" is not a valid YAML key. "
                . 'Use only alphanumerics, hyphens (-), and underscores (_).'
            );
        }
    }

    /**
     * Formats a port mapping as "hostPort:containerPort/protocol".
     * Protocol is always included for explicitness (docker-compose accepts it).
     */
    private function formatPort(PortMapping $port): string
    {
        return $port->hostPort . ':' . $port->containerPort . '/' . $port->protocol;
    }

    /**
     * Formats a volume mount as "./hostPath:containerPath:mode".
     */
    private function formatVolume(Volume $volume): string
    {
        return $volume->hostPath . ':' . $volume->containerPath . ':' . $volume->mode;
    }

    /**
     * Returns a YAML mapping entry for a single env var.
     *
     * Null value  →  KEY:          (valid bare key, Docker reads from host env)
     * Set value   →  KEY: "value"  (quoted per yamlScalar rules)
     */
    private function formatEnvLine(EnvVar $env): string
    {
        if ($env->value === null) {
            return $env->keyName . ':';
        }

        return $env->keyName . ': ' . $this->yamlScalar($env->value);
    }

    /**
     * Wraps a scalar value in double quotes when it contains characters that
     * would confuse a YAML parser: colon, hash, single-quote, leading/trailing
     * whitespace, or when the value is the empty string.
     */
    private function yamlScalar(string $value): string
    {
        $needsQuotes = $value === ''
            || str_contains($value, ':')
            || str_contains($value, '#')
            || str_contains($value, "'")
            || $value !== trim($value);

        if (!$needsQuotes) {
            return $value;
        }

        // Escape internal double-quotes and backslashes.
        $escaped = str_replace(['\\', '"'], ['\\\\', '\\"'], $value);
        return '"' . $escaped . '"';
    }
}
