<?php

declare(strict_types=1);

namespace Manifesto\Services;

use Manifesto\Models\EnvVar;
use Manifesto\Repositories\ProjectRepository;
use Manifesto\Repositories\ServiceChildrenRepository;

/**
 * Generates a .env file string grouped by service from the project hierarchy
 * stored in the database. Stateless: every call to generate() is self-contained.
 *
 * Output format:
 *   # Generated by Manifesto · <project> · <timestamp>
 *   # Source: docker-compose project "<slug>"
 *
 *   # === Service: <name> ===
 *   # SECRET — store in vault, do not commit
 *   SECRET_KEY=change-me
 *   PLAIN_KEY=value
 *   EMPTY_KEY=
 *
 * Rules:
 *   - Services with no env vars emit "# (no env vars)" instead of being skipped.
 *   - Secret vars get a warning comment line immediately before them.
 *   - Values containing '#' or starting with a space are double-quoted;
 *     internal double-quotes are doubled (dotenv convention).
 *   - Null value → KEY=  (empty value, Docker will pull from host environment).
 */
final class EnvFileGenerator
{
    public function __construct(
        private ProjectRepository $projects,
        private ServiceChildrenRepository $children,
    ) {
    }

    /** @throws \RuntimeException when the project does not exist */
    public function generate(int $projectId): string
    {
        $project = $this->projects->find($projectId);
        if ($project === null) {
            throw new \RuntimeException("Project #{$projectId} not found.");
        }

        $serviceRows = $this->projects->servicesOf($projectId);

        $lines = [];
        $lines[] = '# Generated by Manifesto · ' . $project->name . ' · ' . date('c');
        $lines[] = '# Source: docker-compose project "' . $project->slug . '"';

        foreach ($serviceRows as $row) {
            $serviceId   = (int) $row['id'];
            $serviceName = (string) $row['name'];
            $envVars     = $this->children->envsOf($serviceId);

            $lines[] = '';
            $lines[] = '# === Service: ' . $serviceName . ' ===';

            if ($envVars === []) {
                $lines[] = '# (no env vars)';
                continue;
            }

            foreach ($envVars as $env) {
                if ($env->isSecret) {
                    $lines[] = '# SECRET — store in vault, do not commit';
                }
                $lines[] = $this->formatEnvLine($env);
            }
        }

        return implode("\n", $lines) . "\n";
    }

    // -------------------------------------------------------------------------
    // Private helpers
    // -------------------------------------------------------------------------

    /**
     * Formats one env var as  KEY=value  or  KEY=  for null values.
     *
     * A value is quoted (double-quoted) when it:
     *   - contains a '#' (would be treated as a comment by many .env parsers)
     *   - starts with a space (leading whitespace is otherwise stripped)
     * Internal double-quotes are doubled following dotenv convention.
     */
    private function formatEnvLine(EnvVar $env): string
    {
        if ($env->value === null) {
            return $env->keyName . '=';
        }

        return $env->keyName . '=' . $this->dotenvValue($env->value);
    }

    /**
     * Returns the value portion of a dotenv line, quoting only when necessary.
     */
    private function dotenvValue(string $value): string
    {
        $needsQuotes = str_contains($value, '#')
            || (str_starts_with($value, ' '));

        if (!$needsQuotes) {
            return $value;
        }

        // Double internal double-quotes (dotenv convention).
        $escaped = str_replace('"', '""', $value);
        return '"' . $escaped . '"';
    }
}
